replicaCount: 1
image:
  repository: registry.gitlab.com/cscs-599/web-crawler/develop-crawler-manager
  tag: "123"
  pullPolicy: Always
  secrets:
    - name: docker-gitlab
podAnnotations: {}
application:
  track: stable
  tier: manager
  secretName: credentials
params:
  job_id: ""
service:
  name: crawler-manager
  type: LoadBalancer
  # type: NodePort
  externalPort: 80
  internalPort: 8002