services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  image: python:3.7.2-stretch
  before_script:
    - cd backend && pip install -r requirements.txt
    - export PYTHONPATH='.'
  script:
    - python tests/testMain.py

buildBackend:
  stage: build
  image: docker:latest
  before_script:
    - apk add git bash nodejs nodejs-npm --no-cache
  script:
    - ./buildBackendImage
  only:
    - develop
