services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  image: python:3.7.2-stretch
  before_script:
    - cd main && pip install -r requirements.txt
    - export PYTHONPATH='.'
  script:
    - python tests/testMain.py

buildMain:
  stage: build
  image: docker:latest
  before_script:
    - apk add git bash nodejs nodejs-npm --no-cache
  script:
    - ./buildMainImage
  only:
    - develop

buildCrawler:
  stage: build
  image: docker:latest
  before_script:
    - apk add git bash nodejs nodejs-npm --no-cache
  script:
    - ./buildCrawlerImage
  only:
    - develop


buildCrawlerManager:
  stage: build
  image: docker:latest
  before_script:
    - apk add git bash nodejs nodejs-npm --no-cache
  script:
    - ./buildCrawlerManagerImage
  only:
    - develop
