services:
  - docker:dind

stages:
  - test

test:
  stage: test
  image: python:2.7.15-jessie
  before_script:
    - cd backend && pip install -r requirements.txt
    - export PYTHONPATH='.'
  script:
    - python tests/testMain.py