services:
  - docker:dind

stages:
  - test

test:
  stage: test
  image: python:3.7.2-stretch
  before_script:
    - cd backend && pip install -r requirements.txt
    - export PYTHONPATH='.'
  script:
    - python tests/testMain.py