apiVersion: batch/v1
kind: Job
metadata:
  name: crawler-manager
spec:
  template:
    metadata:
      name: crawler-manager
    spec:
      containers:
      - name: crawler-manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        restartPolicy: Never
        command: ["sleep",  "60"]
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: REDIS_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_NAME
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_HOST
        - name: JOB_ID
          value: "{{ .Values.params.job_id }}"
        resources:
          requests:
            cpu: 200m
            memory: 640Mi
          limits:
            cpu: 500m
            memory: 1Gi
      imagePullSecrets:
      - name: docker-gitlab