apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: development
type: Opaque
data:
  REDIS_HOST: MTAuMC4wLjM=
  DB_USER: cm9vdA==
  DB_PASSWORD: V2ViLUNyYXdsZXItMjAxOS1jczU5OQ==
  DB_NAME: Y3Jhd2xlcl90ZXN0Cg==
  MYSQL_HOST: MTAuMzEuMjI0LjMK