apiVersion: batch/v1
kind: Job
metadata:
  name: "crawler-{{date "20060102150405" .Release.Time }}"
spec:
  template:
    metadata:
      name: crawler
    spec:
      containers:
      - name: crawler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: REDIS_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_NAME
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_HOST
        - name: URLS
          value: "{{ .Values.params.urls }}"
        resources:
          requests:
            cpu: 200m
            memory: 640Mi
          limits:
            cpu: 200m
            memory: 1Gi
      restartPolicy: Never
      imagePullSecrets:
      - name: docker-gitlab