apiVersion: batch/v1
kind: Job
metadata:
  name: "crawler-{{date "20060102150405" .Release.Time }}"
  namespace: "{{ .Values.application.namespace }}"
  labels:
    jobId: "{{ .Values.params.jobId }}"
spec:
  backoffLimit: 5
  template:
    metadata:
      name: crawler
      labels:
        app: "crawler-{{date "20060102150405" .Release.Time }}"
    spec:
      containers:
      - name: crawler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #command: ["/bin/sh", "-c", "python", "app.py"]
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: REDIS_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_NAME
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_HOST
        - name: ENVIRONMENT
          value: "prod"
        - name: JOB_IP
          value: "crawler-{{date "20060102150405" .Release.Time }}.{{ .Values.application.namespace }}"
        - name: URL
          value: "{{ .Values.params.url }}"
        - name: CRAWLER_MANAGER_ENDPOINT
          value: "{{ .Values.params.crawlerManagerEndpoint }}"
        - name: NAMESPACE
          value: "{{ .Values.application.namespace }}"
        - name: CRAWLER_HOSTNAME
          value: "{{ .Values.params.crawlerHostname }}"
        resources:
          requests:
            cpu: 200m
            memory: 640Mi
          limits:
            cpu: 200m
            memory: 1Gi
      restartPolicy: Never
      imagePullSecrets:
      - name: docker-gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: "crawler-{{date "20060102150405" .Release.Time }}"
  namespace: "{{ .Values.application.namespace }}"
  labels:
    app: crawler-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: "crawler-{{date "20060102150405" .Release.Time }}"