replicaCount: 5
image:
  repository: registry.gitlab.com/cscs-599/web-crawler/develop-crawler
  tag: "123"
  pullPolicy: Always
  secrets:
    - name: docker-gitlab
podAnnotations: {}
application:
  track: stable
  tier: crawler
  secretName: credentials