apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-application
  labels:
    app: main-application
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: main-application
  template:
    metadata:
      labels:
        app: main-application
      name: main-application
    spec:
      containers:
      - name: main-application
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #command: ["/bin/sh","-c"]
        #args: ["./initialize-django.sh && python project/manage.py runserver 0.0.0.0:8001"]
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: REDIS_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DB_NAME
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_HOST
        resources:
          requests:
            cpu: 200m
            memory: 640Mi
          limits:
            cpu: 500m
            memory: 1Gi
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}